######################################################################
# Automatically generated by qmake (3.0) ?? 7? 18 10:19:31 2024
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 01Hello
INCLUDEPATH += .

# Input
SOURCES += main.cpp
