######################################################################
# Automatically generated by qmake (3.0) ?? 7? 18 11:34:33 2024
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 02Parent
INCLUDEPATH += .

# Input
SOURCES += main.cpp
