######################################################################
# Automatically generated by qmake (3.0) ?? 7? 18 14:29:07 2024
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 03Close
INCLUDEPATH += .

# Input
SOURCES += main.cpp
