######################################################################
# Automatically generated by qmake (3.0) ?? 7? 18 15:57:28 2024
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 04Age
INCLUDEPATH += .

# Input
SOURCES += main.cpp
